const tagTypes = [
    { tagName: "div" },
    { tagName: "h1" },
    { tagName: "h2" },
    { tagName: "h3" },
    { tagName: "h4" },
    { tagName: "h5" },
    { tagName: "h6" },
    { tagName: "button" },
    { tagName: "input" },
    { tagName: "a" },
    { tagName: "p" },
    { tagName: "i" },
    { tagName: "svg" },
];
